### ISSUE TITLE
Description is misleading (about the HMAC challendge-reaponse)

### ISSUE THREAD

**Issue by ava1ar** [saravanan30erd/solokey-full-disk-encryption#3]
Hi, thanks for the useful project! Juat want to report the problem in description - unlike ykfde, this project doesn't relay  on HMAC Challenge-Response mode and use FIDO2 instead via fido2luks library. Please fix the description and remove link to solo-python which is not used here at all.

**Comment by saravanan30erd** [comment]
@ava1ar  I used fido2luks instead of solo-python due to its simplicity and easy to use at initrmfs stage. But indeed its using HMAC challenge-response mode in solokey.

https://github.com/solokeys/solo-python#challenge-response

For using challenge response mode, you can use below solo commands.
solo key make-credential  - it generates hex-encoded credential id.
solo key challenge-response credential_id challenge - Pick a challenge, and generate the associated response.

Using fido2luks, we can do the same challenge response in solo.
fido2luks credential - it generates hex-encoded credential id.
fido2luks print-secret credential_id --salt string:challenge - Pick a challenge, and generate the associated response.

For same credential & challenge, you will always get the same response in solokey. So I tested the output (response) from fido2luks by passing the credential generated by solo python with same challenge and vice versa, it always provides same response regardless of tool. Tool might be different but underlying mechanism is same - challenge response mode.

**Comment by ava1ar** [comment]
Well, this makes sense, however still requires some clarification.

For ykdfe, HMAC challendge-reaponse is one of the features of yubikey itself (HMAC-SHA1 Challenge-Response) and can't be easily ported to non-yubikeys devices. 
The fido2luks library you are using here, relies on hmac-secret extention of the FIDO2. So, while the result is similar (challendge reaponse via the key), internal implementation ia very diffirent.

Also worth mention that after you switch to fido2luks, your app is now compatible with other keys with hmac-secret support for FIDO2 (including yubikey with proper firmware version). Also technically it is FIDO2 full disk encryption software now (which is great, btw) and you should mention this as well.

So my proposal is to rephrase the description to something like "leverages FIDO2 hmac-secret extension for creating strong..." - this would be more correct description. Also worth mention that other keys are potentially supported as well, not just SoloKey.

Hope this make things more clear.
